### ISSUE TITLE
Does not recalculate after scrolling

### ISSUE THREAD

**Issue by TurboThomsen** [phenax/pattern-lock-js#35]
if you refresh the page with much content and you start below, the bounds do not recalculate correctly.

**Comment by phenax** [comment]
Can you create a simple reproducable example in a jsfiddle or codesandbox?

**Comment by TurboThomsen** [comment]
The [Demo Page](https://www.cssscript.com/demo/pattern-lock-patternlockjs/) is a good example, if you put a padding-top="1000px" to the pattern-container.
Executing recalculateBounds() after touchstart and mousedown is maybe a option to fix it. This is so far the option after resizing the window.

**Comment by phenax** [comment]
That's a good idea! Let me know if you can create a pr with this change. If not, I'll try to pick this up this weekend.

**Comment by TurboThomsen** [comment]
https://github.com/phenax/pattern-lock-js/pull/36#issue-1274728039
