### ISSUE TITLE
Add a fill for the starting point.

### ISSUE THREAD

**Issue by profesoryeow** [phenax/pattern-lock-js#41]
Oddly enough, it is very useful to save the result as an image (base64) and use it to share in forms / spreadsheets / reports.
It would be very useful if the starting point has a complete fill or a different color.
Can you add that feature please?

**Comment by phenax** [comment]
Sorry about the delay. I've created pr that adds an option for enabling arrows which I think might work for making the direction of the pattern clear. I've also added an `image` property for the onComplete callback.

**Comment by profesoryeow** [comment]
Thanks @phenax  !!!
